gb:
  max_depth:
  - 10
  - 50
  - 100
  - null
  min_samples_leaf: 
  - 1
  - 2
  - 5
  - 10
  - 20
  min_samples_split:
  - 2
  - 5
  - 10
  - 15
  - 20
  n_estimators:
  - 100
  - 250
  - 500
  - 1000
  loss: 
  - "squared_error"
  - "absolute_error"
  - "huber"
  learning_rate:
  - 1.
  - .1
  - .01
  - .001
  criterion:
  - "friedman_mse"
  - "squared_error"
  - "mae"