dum:
  strategy:
  - mean
gb:
  criterion:
  - friedman_mse
  learning_rate:
  - 0.1
  loss:
  - squared_error
  max_depth:
  - 3
  min_samples_leaf:
  - 1
  min_samples_split:
  - 2
  n_estimators:
  - 100
  tol:
  - 0.001
lr:
  fit_intercept:
  - true
mlp:
  activation:
  - relu
  hidden_layer_sizes:
  - - 100
  learning_rate_init:
  - 0.001
  max_iter:
  - 1000
  solver:
  - adam
rf:
  max_depth:
  - null
  max_features:
  - auto
  max_samples:
  - 1.0
  min_samples_leaf:
  - 1
  min_samples_split:
  - 2
  n_estimators:
  - 100
  oob_score:
  - true
ridge:
  alpha:
  - 1.0
  fit_intercept:
  - true
tree:
  ccp_alpha:
  - 0.0
  max_depth:
  - null
  max_features:
  - auto
  min_samples_leaf:
  - 1
  min_samples_split:
  - 2
