dum:
  strategy:
  - mean
lr:
  fit_intercept:
  - true
ridge:
  alpha:
  - 1.0
  fit_intercept:
  - true
tree:
  ccp_alpha:
  - 0.0
  max_depth:
  - null
  max_features:
  - auto
  min_samples_leaf:
  - 1
  min_samples_split:
  - 2
