gb:
  criterion:
  - friedman_mse
  learning_rate:
  - 0.1
  - 0.01
  - 0.001
  loss:
  - squared_error
  - absolute_error
  max_depth:
  - 3
  - 10
  - 20
  - null
  min_samples_leaf:
  - 2
  - 5
  - 10
  - 15
  min_samples_split:
  - 2
  - 5 
  - 10
  - 15
  n_estimators:
  - 250
  - 500
  - 1000
  tol:
  - 0.001