rf:
  max_depth:
  - 3
  - 5
  - 10
  - 15
  - 20
  - 100
  - null
  min_samples_leaf:
  - 1
  - 5
  - 10
  - 15 
  - 20
  min_samples_split:
  - 2
  - 5 
  - 10
  - 15 
  - 20
  n_estimators:
  - 250
  - 500
  - 750
  - 1000
  max_features:
  - auto
  - sqrt
  - log2
  max_samples:
  - 1.0
  - .8
  - .5
  criterion:
  - squared_error
  - absolute_error
  oob_score:
  - true