mlp:
  activation:
  - relu
  - identity
  - tanh
  hidden_layer_sizes:
  - - 200
  - - 100
    - 100
  - - 50
  - - 100
  - - 50
  - - 500
  - - 100
    - 300
    - 100
  - - 200
    - 100
    - 200
  learning_rate_init:
  - 0.001
  - 0.01
  - 0.05
  - 0.1
  max_iter:
  - 1000
  - 5000
  solver:
  - adam
  - sgd