mlp: 
  activation:
  - relu
  - logistic
  hidden_layer_sizes:
  - - 100
    - 100
  - - 200
  - - 50
    - 100
    - 50
  learning_rate_init:
  - .001
  - .01
  max_iter:
  - 1000
  - 5000
  solver:
  - adam
  - sgd